### ISSUE TITLE
In InduceDefect remove atoms by index, not position

### ISSUE THREAD

**Issue by gjenness** [uw-cmg/MAST#221]
Lets assume we have an unrelaxed perfect structure, and lets say we want to create a vacancy at (x,y,z).  If the structure undergoes a moderate amount of relaxation, then it's possible that the position (x,y,z) will no longer "exist", i.e. the atom at that position might be displaced by (dx, dy, dz) such that the final coordinates are (x+dx, y+dy, z+dz).  

In such a situation, the InduceDefect ingredient will not be able to create a vacancy at that location.  The reason why is that InduceDefect searches for an atom index that matches that coordinate within a given tolerance, and if it's outside of that tolerance it won't find the atom (and will thus throw an error).

An alternative solution is to check for the position BEFORE the relaxation occurs i.e. during ingredient creation we find what index matches the given coordinates before anything is ran, and store that in the defect dictionary.  Then when we call InduceDefect, we will simply extract which index to use and then remove the atom according to the index.

**Comment by cmgtam** [comment]
Close with major atom indexing fixes in version 1.3.4.
