### ISSUE TITLE
Additional "max jobs" option for platform submit templates

### ISSUE THREAD

**Issue by henry-wu** [uw-cmg/MAST#397]
Some additional options may need to be added regarding how MAST submits to different clusters.  Specifically, some setting in the platform template regarding the max number of queued jobs, and a reasonable way for MAST to deal with the limitation.

The example is XSEDE stampede, which has a 50 total queued+running job limitation.  When MAST tries to submit over that limit, it will currently error out because of extract_submitted_jobid.  This is because split()[-1] will not find a jobid at the end of stampede's output, instead it'll find something like "...max 50 jobs", which returns "jobs", and python errors out because "jobs" is not an integer.

After MAST errors out, mastmon is not launched and the submitlist is not cleared (or changed at all).  But some jobs within submitlist were actually submitted to stampede and will be running.  This is problematic since they will be double submitted the next time MAST is run (unless the user manually changes submitlist).

Summarizing,
- there should be some kind of "max submit jobs" parameter in the platform template.
- there should be a simple way for MAST to determine how many jobs are currently running.
- MAST needs to submit up to the "max submit jobs" limit (minus one for mastmon to run), remove only the submitted jobs from submitlist, and append new jobs from mastmon to the end of submitlist (rather than overwriting the file).

**Comment by cmgtam** [comment]
Closed with #447 - open new issues for implementation problems.
