### ISSUE TITLE
StructOpt-MAST Genealogy Tree Issue

### ISSUE THREAD

**Issue by akacz** [uw-cmg/MAST#420]
The Genealogy tree does not seem to be updating correctly while optimizing VASP (or LAMMPS possibly?). The structures apparently went through crossovers and mutations as indicated by the structure and the 'crossover attempts' on Optimizer-restart file. However in the Genealogy tree file looks as below. 
0 1 2 3 4 5 6 7
2 4 7 3 0 6 1 5
0 1 2 3 5 6 7 0 

The individual stored in the restart-files folder should contain the necessary genealogy information but for some reason it is getting lost.

**Comment by cmgtam** [comment]
Transferred issue to https://github.com/uw-cmg/StructOpt_modular. Closing here.
