### ISSUE TITLE
StructOpt-MAST Log file complexity

### ISSUE THREAD

**Issue by akacz** [uw-cmg/MAST#421]
In the log files, I understand the purpose of warning messages such as " 2014-09-25 13:40:59,137 : structoptchecker: /home/hko/MAST/SCRATCH/StructoptTest_SiC_20140922T200036/perfect_opt1/02:  WARNING : Ignoring program key encut for INPUT. To allow this keyword, add it to /home/hko/bin/pylib/MAST/CONTROL/programkeys/structopt_allowed_keywords.py", but I think there are too many lines of these warnings (they are also lengthy!), making it hard for user to find important information. Could we think of something like, only print once at the beginning of MAST run?

**Comment by cmgtam** [comment]
Will not fix: all future StructOpt development is being handled at https://github.com/uw-cmg/StructOpt_modular.
structopt by itself does not log nearly as much as MAST does
