### ISSUE TITLE
StructOpt-MAST Duplicate directories

### ISSUE THREAD

**Issue by akacz** [uw-cmg/MAST#422]
Duplicate directories outside of the optimization folder are generated for each generation of structures as a result of running the VASP and LAMMPS checkers.  Is there a way to prevent the creation of these archive directories?  Furthermore for the single archives in the optimization folder is there a way to label these with the generation information ( e.g. gen01_<time> ) ?

**Comment by cmgtam** [comment]
Will not fix: all future StructOpt development is being handled at https://github.com/uw-cmg/StructOpt_modular.
